# Generated by Django 3.1.1 on 2020-09-22 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_participant_last_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='last_read',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='chat.message'),
        ),
    ]
